### ISSUE TITLE
Upgrade oauthlib version as a dependency requirement

### ISSUE THREAD

**Issue by ThomasWunderlich** [pokitdok/pokitdok-python#28]
Hi,
I'd like to upgrade the oauthlib version requires as versions prior to 0.7.0 have a security issue where oauth client passwords were logged

**Comment by corbinbs** [comment]
Hi @ThomasWunderlich - contributions are definitely welcome

If you'd like to post a PR with the upgraded requirement(s), I can help review/test/publish it.

Thank you

**Comment by ThomasWunderlich** [comment]
@corbinbs Just added PR #29. I'm not sure if you prefer locking dependencies or if you would prefer a range. I suspect in this case, it makes sense to lock it, but let me know

**Comment by corbinbs** [comment]
Hi @ThomasWunderlich - I've merged the PRs we've been reviewing / discussing.  
I'm working on a new PyPI release with these adjustments now.   I'll post back here when that's available for your use.   Thanks!

**Comment by corbinbs** [comment]
@ThomasWunderlich - https://pypi.python.org/pypi/pokitdok/2.7.2 is now available with the oauthlib 0.7.2 dependency.   Should pick it up now when doing a `pip install pokitdok` 

Thanks again for pointing this out and please let us know if you run across anything else.

**Comment by ThomasWunderlich** [comment]
Awesome! Thanks so much for all the work you put into this PR!
