### ISSUE TITLE
Mixed Content Types and Accept Types for Activities

### ISSUE THREAD

**Issue by aannapureddy** [pokitdok/pokitdok-python#31]
Is there a clean way to pass header information for Content Type and Accept in Python as a parameter to activities? 

I am trying to retrieve old JSON response activities with an activity_id except as X12.

**Comment by corbinbs** [comment]
Hi @aannapureddy 

when you're making new eligibility requests, you can use:
```
import pokitdok
pd = pokitdok.api.connect('******', '**************', auto_refresh=True)
# what I'm sending...
pd.json_headers['Content-type'] = "application/json"
# what I want back...
pd.json_headers['Accept'] = "application/vnd.pokitdok.v4+edi-x12-json"
# continue making API requests
pd.eligibility({...})
```
to submit and receive different formats.   For transactions that have already processed and you need to review them later on via the activities API, you can use:
```
pd.base_headers['Accept'] = "application/vnd.pokitdok.v4+activity-x12-json"
pd.activities(activity_id='**************')
```
and you'll receive all of the typical activity data plus the `x12_request` and the `x12_response`
