### ISSUE TITLE
Setting OAuth token to None causes TypeError in oauthlib 2.1.0

### ISSUE THREAD

**Issue by Sourceless** [pokitdok/pokitdok-python#32]
# Reproduction
## Lib versions
```
pokitdok==2.7.2
oauthlib==2.1.0
```

## Code
Use example code as shown in readme on a fresh install.

# Issue 
## Description
When the pokitdok client attempts to set the token of the oauth client to None, it triggers a property setter on the oauth client which treats the `None` as some sort of HTTP response.

## Traceback (snipped for relevance)
```
File "/Users/laurence/src/patient-price/env/lib/python3.6/site-packages/pokitdok/api/client.py", line 143, in fetch_access_token
    self.api_client.token = None
  File "/Users/laurence/src/patient-price/env/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 114, in token
    self._client._populate_attributes(value)
  File "/Users/laurence/src/patient-price/env/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 468, in _populate_attri
butes
    return self.populate_token_attributes(response)
  File "/Users/laurence/src/patient-price/env/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 479, in populate_token$
attributes
    if 'access_token' in response:
TypeError: argument of type 'NoneType' is not iterable
```

## Location of issue
https://github.com/pokitdok/pokitdok-python/blob/master/pokitdok/api/client.py#L142

# Mitigation
I had success in circumventing the issue by removing the offending line; however I have not submitted this as a PR because I haven't yet had the time to understand why the line was there in the first place and whether by removing it, errors would be caused further down the line.

Here is a commit on a forked repo that makes this change: https://github.com/PatientPrice/pokitdok-python/commit/7685b4adc8462a482a6317d1b5d301d49acec0aa

**Comment by corbinbs** [comment]
Hi @Sourceless - thanks for the report!

I believe https://github.com/pokitdok/pokitdok-python/blob/master/pokitdok/api/client.py#L142 was originally introduced a while back (like 2 years ago) to address a problem with automatic token refreshing.   It could be that this is no longer an issue with recent oauthlib versions.

If you'd like to open up that MR, we can help review and test it to ensure everything still works as expected using the latest oauthlib

**Comment by Sourceless** [comment]
Thanks for your quick response :) PR is here: https://github.com/pokitdok/pokitdok-python/pull/33
