### ISSUE TITLE
Error while parsing cancellation result

### ISSUE THREAD

**Issue by arpit-goel** [pokitdok/pokitdok-python#8]
While cancelling a scheduled appointment, the package parses the response returned from PokitDok using Response class json method, can be seen [here](https://github.com/pokitdok/pokitdok-python/blob/master/pokitdok/api/client.py#L411). But the Cancellation API doesn't return any data on successful cancellation, just 204 response. When the package tries to parse the response, it raises an error saying that the **ValueError: No JSON object could be decoded**.
This should be conditionally parsed, i.e., if response is not 204 and has some content then only parse it as json.

**Comment by corbinbs** [comment]
Thanks for the feedback, @arpit-goel !
We'll get that fixed up and roll out a new version.

**Comment by ghadishayban** [comment]
@arpit-goel the API has been changed to return a `200` status rather than a `204` (with the usual metadata about rate limiting).  Please try it out and let us know.  There should be no necessary changes to the client.

**Comment by arpit-goel** [comment]
@ghadishayban Thanks for the quick fix. Works like a charm.
